/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from "react";
import Link from "next/link";
import { styled } from "@mui/material/styles";
import { MuiProps } from "../types";

const Mui1: any = styled("div")({
  background: `linear-gradient(-2.239999999999995deg, rgba(255, 255, 255, 1) -0.003523703957980974%, rgba(255, 255, 255, 0) 97.93843538224347%)`,
  border: `1px solid rgba(217, 225, 236, 0.2)`,
  boxSizing: `border-box`,
  borderRadius: `8px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: "100%",
  height: `270px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
});

const Div: any = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 16px 0px`,
  boxSizing: `border-box`,
  left: `17px`,
  top: `17px`,
});

const WhatKindOfImpactProj: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 41, 60, 1)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `700`,
  fontSize: `17px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  width: `247px`,
  height: `39px`,
  margin: `0px`,
});

const Span: any = styled("div")({
  backgroundColor: `rgba(75, 88, 124, 0.05)`,
  borderRadius: `12px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `4px 8px`,
  boxSizing: `border-box`,
  width: `110px`,
  left: `84px`,
  top: `80px`,
});

const WorldWide: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 97, 84, 1)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Vector: any = styled("img")({
  height: `11px`,
  width: `6px`,
  margin: `0px 0px 0px 6px`,
});

const Location: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(167, 172, 180, 1)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `19px`,
  top: `84px`,
});

const Label: any = styled("div")({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `329px`,
  left: `17px`,
  top: `120px`,
});

const Input1: any = styled("div")({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(217, 225, 236, 1)`,
  boxSizing: `border-box`,
  borderRadius: `4px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `12.5px 59.3125px 11.5px 8px`,
  width: `329px`,
  margin: `0px`,
});

const EducationSustainabil: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(75, 88, 124, 0.38)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const SeeMore: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 94, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  position: `absolute`,
  left: `139px`,
  top: `231px`,
});

const Frame2: any = styled("div")({
  backgroundColor: `rgba(217, 225, 236, 1)`,
  borderRadius: `40px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 14px`,
  boxSizing: `border-box`,
  left: `37px`,
  top: `179px`,
});

const Education: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame3: any = styled("div")({
  backgroundColor: `rgba(217, 225, 236, 1)`,
  borderRadius: `40px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 14px`,
  boxSizing: `border-box`,
  left: `133px`,
  top: `179px`,
});

const Sustainability: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame4: any = styled("div")({
  backgroundColor: `rgba(217, 225, 236, 1)`,
  borderRadius: `40px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 14px`,
  boxSizing: `border-box`,
  left: `249px`,
  top: `179px`,
});

const Hunger: any = styled("div")({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Helvetica`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

function Mui(props: MuiProps): JSX.Element {
  return (
    <Mui1 className={props.className}>
      <Div>
        <WhatKindOfImpactProj>
          {`What kind of impact projects would you like to support?`}
        </WhatKindOfImpactProj>
      </Div>
      <Span>
        <WorldWide>{`World Wide`}</WorldWide>
        <Vector src={`/Mui_Vector.png`} loading="lazy" alt={"Vector"} />
      </Span>
      <Location>{`Location:`}</Location>
      <Label>
        <Input1>
          <EducationSustainabil>
            {`Education, Sustainability, Gender equality`}
          </EducationSustainabil>
        </Input1>
      </Label>
      <Link href="/posi">
        <SeeMore>{`See more`}</SeeMore>
      </Link>
      <Frame2>
        <Education>{`Education`}</Education>
      </Frame2>
      <Frame3>
        <Sustainability>{`Sustainability`}</Sustainability>
      </Frame3>
      <Frame4>
        <Hunger>{`Hunger`}</Hunger>
      </Frame4>
    </Mui1>
  );
}

export default Mui;
